apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: gitops-demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: gitops-demo-app
    spec:
      containers:
      - name: app
        image: sasubillis/gitops:master-04884a5f-1647682669 # {"$imagepolicy": "flux-system:image-repo-policy"}
        ports:
        - containerPort: 5000
